import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import "@h001/ui/dist/index.css";


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html>
			{/* 여긴 font, theme, globalcss, provider 만 */}
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
			>
				{children}
			</body>
		</html>
	);
}
