{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "opencsp-console.fullname" . }}
  labels:
    {{- include "opencsp-console.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                # 1. path 내부에 별도의 backend.service.name이 선언되어 있으면 그것을 사용
                # 2. 없으면 기존처럼 기본 fullname-fe 사용
                name: {{ if .backend }}{{ .backend.service.name }}{{ else }}{{ include "opencsp-console-be.fullname" $ }}-fe{{ end }}
                port:
                  number: {{ if .backend }}{{ .backend.service.port.number }}{{ else }}{{ $.Values.fe.service.port }}{{ end }}
          {{- end }}
    {{- end }}
{{- end }}