{{- if eq .Values.pam.provider "teleport" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pam.teleport.serviceAccountName }}
  labels:
    {{- include "opencsp-console.labels" . | nindent 4 }}
    app.kubernetes.io/component: pam-teleport
{{- end }}